### ISSUE TITLE
Key navigation fails

### ISSUE THREAD

**Issue by marc-brouard** [marromlam/sailor.vim#1]
Thanks for creating this plugin, but I can not seem to get it to work. I have followed the instructions to install but even just switching between kitty windows I am getting the following error
```
Key action failed

kitten kittens/pass_keys.py top ctrl+k
list index out of range

Press Enter to close
```
I am using version 0.24.4 of Kitty

**Comment by marc-brouard** [comment]
So I think I may have figure this out, there is an error in the setup documentation, the following section

```
map ctrl+j kitten kittens/pass_keys.py bottom ctrl+j
map ctrl+k kitten kittens/pass_keys.py top    ctrl+k
map ctrl+h kitten kittens/pass_keys.py left   ctrl+h
map ctrl+l kitten kittens/pass_keys.py right  ctrl+l
```
Should be
```
map ctrl+j kitten kittens/pass_keys.py kittens/neighboring_window bottom ctrl+j
map ctrl+k kitten kittens/pass_keys.py kittens/neighboring_window top    ctrl+k
map ctrl+h kitten kittens/pass_keys.py kittens/neighboring_window left   ctrl+h
map ctrl+l kitten kittens/pass_keys.py kittens/neighboring_window right  ctrl+l
```
Instead.
Perhaps the documentation could be updated, happy to submit a PR if you want

There are still issues moving between vim splits, detecting when you are at the boundary of vim, but I will log that as a separate issue

**Comment by marromlam** [comment]
> I am using version 0.24.4 of Kitty

Actually I need to take a look at that version because I saw few weeks ago some of the api has changed a bit.
I am still in `kitty 0.23.1`


> So I think I may have figure this out, there is an error in the setup documentation, the following section
Sorry for no having the docs updated!

Yes, you are right, the proper way of setting it in the `kitty.conf` is just like you stated. You can also set the name of the tab in order it to work with other apps:
```
map ctrl+k kitten kittens/pass_keys.py neighboring_window top    ctrl+k ".*(nvim)$"
map ctrl+j kitten kittens/pass_keys.py neighboring_window bottom ctrl+j ".*(nvim)$"
map ctrl+h kitten kittens/pass_keys.py neighboring_window left   ctrl+h ".*(nvim)$"
map ctrl+l kitten kittens/pass_keys.py neighboring_window right  ctrl+l ".*(nvim)$"
```


> Perhaps the documentation could be updated, happy to submit a PR if you want

Sure I would appreciate it!


> There are still issues moving between vim splits, detecting when you are at the boundary of vim, but I will log that as a separate issue

I need to take a look at that and also a weird effect I have when in `nvim > tmux > kitty`, where I am not sending properly the keys (though the (n)vim module works fine)

**Comment by marc-brouard** [comment]
Pull request submitted, updated documentation
